### Registrar usuario en aplicacion
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "usunom": "Jeisson Acosta",
    "usuemail": "json@gmail.com",
    "usupwd": "123456"
}

### Iniciar sesion en la aplicacion
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "usuemail": "json@gmail.com",
    "usupwd": "123456"
}

### Crear una app con su informacion
POST http://localhost:5000/main/create-app
Content-Type: application/json

{
    "connom": "Netflix",
    "conusuario": "jeidacosta@hotmail.com",
    "conpwd": "contranet",
    "connom_icon": "movie",
    "usuid": 1,
    "catid": 1
}

### Actualizar la info de una app creada
PATCH http://localhost:5000/main/update-app
Content-Type: application/json

{
    "conid": 1,
    "connom": "Netflix",
    "conusuario": "jeidacosta@hotmail.com",
    "conpwd": "contranet",
    "connom_icon": "song",
    "usuid": 1,
    "catid": 1

}

### Eliminar una app creada
DELETE http://localhost:5000/main/delete-app/2

### Crear una categoria
POST http://localhost:5000/category/create
Content-Type: application/json

{
    "catcod": "PERS",
    "catnom": "Personal",
    "usuid": 1
}

### Actualizar una categoria
PATCH http://localhost:5000/category/update
Content-Type: application/json

{
    "catid": 2,
    "catcod": "PERS",
    "catnom": "Personal"
}

### Eliminar una categoria
DELETE http://localhost:5000/category/delete/2

### Cargar informacion de la opcion de la boveda
GET http://localhost:5000/main/get-info-vault/1

### Obtener una contraseña de una app
GET http://localhost:5000/main/get-password/1/1